---
kind: Service
apiVersion: v1
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    app: ftps
  ports:
    - port: 21
      protocol: TCP
      targetPort: 21
      name: ftps
    - port: 30000
      name: first
      targetPort: 30000
    - port: 30001
      name: second
      targetPort: 30001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: local-ftps
          livenessProbe:
              exec:
                command:
                  - /bin/sh
                  - /livenessprobe.sh
              initialDelaySeconds: 5
              periodSeconds: 5
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 30000
            - containerPort: 30001
  selector:
    matchLabels:
      app: ftps 